server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/userdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  application:
    name: SECURITY-SERVICE
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG